import { RawProp } from "./RawProp";
import { RawShapeBox, RawShapeSphere } from "../RawShape/RawShape";
import { BlockType } from "../../BlockType";
import { Chunck } from "../../Chunck";
import { IVoxelDrawingDataSerialized } from "./VoxelDrawing";

export var treesVoxelDrawingDatas = [
    {
        offset: {
            i: -4,
            j: -2,
            k: 0,
        },
        wI: 7,
        dJ: 6,
        hK: 7,
        dataString: "[6]EBAQBxAQ[d]EBAQBxAQ[d]EBAQBxAQ[d]EBAQBxAQ[c]EBAQEBAH[2]EBAQEAcQ[5]EBAQEAcQ[2]EBAQBxAQEBAHBxAQ[2]EBAQEAcQ[10]EBAQBwcQEBAQ[1]EAcQ",
    },
    {
        offset: {
            i: -5,
            j: -2,
            k: 0,
        },
        wI: 15,
        dJ: 11,
        hK: 16,
        dataString:
            "[b]EBAQEBAH[36]EBAQEBAH[36]EBAQEBAH[36]EBAQEBAH[36]EBAQEBAHBxAQ[35]EBAQEBAH[5]EBAQBxAQ[30]EBAQEBAH[5]EBAQEAcQ[30]EBAQEAcH[5]EBAQEAcQ[30]EBAQEAcQ[4]EBAQEAcQ[5]EBAQEAcH[5]EBAQBxAQ[f]EBAQEBAH[15]EBAQEAcQ[4]EBAQBxAQ[5]EBAQBxAQ[a]EBAQEAcQ[4]EBAQEBAH[5]EBAQEBAH[a]EBAQEBAHBxAQ[4]EBAQEAcQ[4]EBAQEBAH[4]EBAQBxAQ[a]EBAQBxAQ[b]EBAQBxAQ[4]EBAQEAcQ[a]EBAQBwcQ[4]EBAQEBAH[a]EBAQBxAH[9]EBAQEBAH[21]EBAQEAcQ[a]EBAQBwcQBxAQ[3]EBAQEAcQ[9]EBAQEAcQ[4]EBAQBxAQ[8]EBAQBxAQ[19]EBAQBxAHBxAQ[16]EBAQEBAH[4]EBAQEAcQ[13]EBAQEBAHEBAQEAcQ[2]EBAQEBAH[1d]EBAQEBAH[10]EBAQEBAH[2]EBAQEAcQ[27]EBAQEBAH[4]EBAQ",
    },
    {
        offset: {
            i: -10,
            j: -12,
            k: 0,
        },
        wI: 16,
        dJ: 22,
        hK: 21,
        dataString:
            "[43]EBAQEAcH[4]EBAQEBAH[6a]EBAQEAcH[4]EBAQEAcHBxAQ[3]EBAQEBAHBwcQ[69]EBAQEBAHBxAQ[3]EBAQEBAHBwcQ[4]EBAQBwcH[4]EBAQEBAH[65]EBAQBwcQ[4]EBAQBwcH[4]EBAQEAcHBxAQ[4]EBAQBxAQ[8]EBAQEBAH[35]EBAQEBAH[25]EBAQEAcH[3]EBAQEBAHEAcHBxAQ[3]EBAQEBAHBwcQ[4]EBAQEAcQ[4]EBAQBxAQ[2e]EBAQEAcQ[4]EBAQEBAHEBAQBxAQ[3]EBAQBwcQEAcQEBAHBxAQEBAQEAcH[20]EBAQEBAHBxAQ[3]EBAQEBAHBwcQ[3]EBAQEBAHBwcH[4]EBAQEBAH[4]EBAQEAcQ[2e]EBAQEBAH[2]EBAQBwcQ[2]EBAQBxAQEBAHBxAQ[2]EBAQ[2]EBAHBxAH[2]EBAQEBAHBwcQ[4]EBAQEAcH[1b]EBAQBxAQ[4]EBAQBwcH[4]EBAQEAcHBxAQ[3]EBAQEAcH[4]EBAQEBAHBxAQ[18]EBAQEBAH[c]EBAQEBAH[4]EBAQEBAH[5]EBAQBxAQ[3]EBAQEBAHBwcQ[3]EBAQEBAHBwcQ[3]EBAQEAcHBwcH[3]EBAQEBAHBwcH[4]EBAQEAcQ[15]EBAQBwcH[4]EBAQEAcHBxAQ[3]EBAQEBAHBwcQ[4]EBAQBxAQ[4]EBAQBwcH[4]EBAQEBAHBxAQ[d]EBAQEBAH[21]EBAQBwcQ[4]EBAQBwcH[4]EBAQBwcH[4]EBAQEAcHBxAQ[3]EBAQEBAHBxAQ[4]EBAQBxAQ[a]EBAQBxAQ[4]EBAQEAcH[4]EBAQEBAHBwcQ[4]EBAQBwcQ[9]EBAQEBAH[5]EBAQBwcQ[3]EBAQEBAHBwcH[4]EBAQBwcH[4]EBAQEAcQ[5]EBAQEAcQ[4]EBAQEBAH[1f]EBAQEBAH[4]EBAQEBAHBxAQ[3]EBAQEBAHBxAQ[4]EBAQBwcQ[4]EBAQEAcH[5]EBAQBwcH[4]EBAQEBAHBxAQ[4]EBAQBwcQ[4]EBAQEAcH[a]EBAQEAcQ[4]EBAQEAcH[4]EBAQBwcHBxAQ[3]EBAQEAcHBwcQ[3]EBAQEBAHEAcQ[4]EBAQBxAQ[4]EBAQEAcQ[2f]EBAQEAcH[4]EBAQEBAHBwcQ[4]EBAQEAcHBxAQ[4]EBAQBwcQ[4]EBAQEAcH[4]EBAQEBAHBxAQ[4]EBAQEAcQ[4]EBAQEAcH[5]EBAQBxAQ[4]EBAQBwcQ[4]EBAQEAcH[4]EBAQEBAH[5]EBAQBxAQ[39]EBAQEAcH[4]EBAQEAcHBxAQ[3]EBAQEBAHBxAQ[a]EBAQBwcQ[4]EBAQEBAHBxAQ[4]EBAQBwcQ[4]EBAQEAcH[4]EBAQEBAHBxAQ[4]EBAQBxAQ[48]EBAQEAcHBxAQ[3]EBAQEAcHBxAQ[4]EBAQBxAQ[b]EBAQBxAQ[4]EBAQEAcQ[58]EBAQEBAH[4]EBAQEAcHBxAQ[6f]EBAQBxAQ[3]EBAQEBAHBwcQ[8]EBAQEBAH[65]EBAQEAcQEAcH[3]EBAQEBAHBwcHBxAQ[2]EBAQEBAHBxAQ[3]EBAQEBAHBwcQ[4]EBAQBwcQ[4]EBAQBxAH[5a]EBAQ[2]EAcHBwcH[3]EBAQ[2]BwcHEAcHBxAQ[66]EBAQEAcH[4]EBAQEBAHBxAHEBAHBxAQ[2]EBAQEBAHBxAQEBAH[5d]EBAQEBAH[4]EBAQEBAH[4]EBAQEBAHBxAQ[a]EBAQBwcQEBAQEAcQ[72]EBAQEAcQ[74]EBAQEAcQ[39]EBAQ",
    },
    {
        offset: {
            i: -2,
            j: -10,
            k: 0,
        },
        wI: 13,
        dJ: 17,
        hK: 17,
        dataString:
            "[2c]EBAQBxAQ[3]EBAQEAcQ[44]EBAQEAcH[4]EBAQBxAQ[44]EBAQEAcQ[3]EBAQEBAH[45]EBAQBxAQ[48]EBAQEBAH[49]EBAQBwcQ[2d]EBAQEBAH[3]EBAQEBAH[12]EBAQEAcQ[8]EBAQEBAH[31]EBAQEAcH[3]EBAQEBAH[9]EBAQEBAH[5]EBAQEAcQ[3]EBAQEAcQ[28]EBAQEAcQ[3]EBAQEBAH[c]EBAQEBAHEBAQEAcQ[5]EBAQEAcQ[3]EBAQEAcQ[7]EBAQEAcQ[4]EBAQBxAQ[11]EBAQBxAQ[20]EBAQBxAQEBAQEAcQ[3]EBAQEAcQ[14]EBAQBxAQ[10]EBAQEBAH[18]EBAQEBAH[a]EBAQEBAH[f]EBAQEBAH[8]EBAQEAcQEAcH[2]EBAQEBAHBwcQ[7]EBAQBxAQ[f]EBAQEBAH[4]EBAQBxAQ[e]EBAQEBAH[4]EBAQEAcQ[6]EBAQEAcQ[1c]EBAQEBAH[4]EBAQBwcHBxAQ[2]EBAQBwcQ[3]EBAQEAcQ[17]EBAQ[2]BxAQ[2]EBAQBxAQEAcQ[2]EBAQBxAQEBAQBxAQ[12]EBAQBxAQ[3]EBAQEAcQ[3]EBAQBxAQ[3]EBAQEAcQ[1b]EBAQEBAH[c]EBAQBxAQ[1b]EBAQEBAH[2c]EBAQEBAH[18]EBAQEAcQ[49]EBAQBxAQ[43]EBAQ[1]EA==",
    },
    {
        offset: {
            i: -1,
            j: -3,
            k: 0,
        },
        wI: 7,
        dJ: 5,
        hK: 20,
        dataString:
            "[5]EBAQBwcQEBAQBwcHEBAQEBAH[4]EBAQEAcQEBAQEAcHBxAQEBAHBwcHEBAQEAcH[4]EBAQBxAQEBAQBwcHEBAQEAcHBwcQEBAQBwcQ[3]EBAQEBAHEBAQEBAHBwcQEBAQBwcHBxAQEBAHBxAQ[3]EBAQEAcQEBAQEAcHBxAQEBAHBwcHEBAQEAcH[4]EBAQBxAQEBAQBwcHEBAQEAcHBwcQEBAQBwcQ[3]EBAQEBAHEBAQEBAHBwcQEBAQBwcHBxAQEBAHBxAQ[3]EBAQEAcQEBAQEAcHBxAQEBAHBwcHEBAQEAcH[6]EBAQBwcHEBAQEAcHBxAQEBAQBwcQ[6]EBAQBwcQEBAQEBAH[9]EBAQBwcQEBAQEAcQ[6]EBAQEAcQEBAQEBAHBxAQ[8]EBAQBwcQEBAQEAcH[8]EBAQEBAHBxAQEBAQBwcQ[b]EBAQBwcQ[8]EBAQEAcQ[2]EBAQBxAQ[8]EBAQBxAQ[2]EBAQBxAQ[7]EBAQEAcQ[2]EBAQEBAH[5]EBAQEBAH[5]EBAQEBAH[5]EBAQEAcQ[a]EBAQ[1]EA==",
    },
    {
        offset: {
            i: -8,
            j: -14,
            k: 0,
        },
        wI: 10,
        dJ: 16,
        hK: 45,
        dataString:
            "[2d]EBAQEBAHBxAQ[2]EBAQBwcQ[2d]EBAQEBAHBxAQEBAQEBAHBwcH[2]EBAQBwcHBxAQEBAQEBAHBxAQ[2a]EBAQBwcQ[2]EBAQBwcHBxAQEBAQEAcHBwcQ[2]EBAQBwcQ[2a]EBAQEAcH[2]EBAQEAcHBwcQEBAQEBAHBwcH[2]EBAQEAcH[2a]EBAQEBAHBxAQEBAQEBAHBwcH[2]EBAQBwcHBxAQEBAQEBAHBxAQ[2a]EBAQBwcQ[2]EBAQBwcHBxAQEBAQEAcHBwcQ[2]EBAQBwcQ[2a]EBAQEAcH[2]EBAQEAcHBwcQEBAQEBAHBwcH[2]EBAQEAcH[2a]EBAQEBAHBxAQEBAQEBAHBwcH[2]EBAQBwcHBxAQEBAQEBAHBxAQ[2a]EBAQBwcQ[2]EBAQBwcHBxAQEBAQEAcHBwcQ[2]EBAQBwcQ[2a]EBAQEAcH[2]EBAQEAcHBwcQEBAQEBAHBwcH[2]EBAQEAcH[2a]EBAQEBAHBxAQ[2]EBAQBwcH[2]EBAQEAcHBxAQ[2]EBAQBxAQ[2a]EBAQBwcQ[2]EBAQEAcHBxAQEBAQEBAHBwcQ[2d]EBAQEAcHBxAQEBAQEBAHBwcQ[2]EBAQBwcQ[2a]EBAQEBAH[2]EBAQEBAHBwcQ[2]EBAQBwcH[2]EBAQEBAH[2b]EBAQBxAQ[2]EBAQBwcH[2]EBAQEAcHBxAQ[2d]EBAQBwcH[2]EBAQEAcHBxAQEBAQEBAHBwcQ[2d]EBAQEAcHBxAQEBAQEBAHBwcQ[2]EBAQBwcH[2d]EBAQEBAHBwcQ[2]EBAQBwcH[2]EBAQEBAH[2e]EBAQBwcH[2]EBAQEAcHBxAQ[2d]EBAQBwcQ[2]EBAQEAcH[2]EBAQEBAHBxAQ[2d]EBAQEAcH[2]EBAQEBAHBxAQ[2]EBAQEAcQ[2d]EBAQEBAHBxAQ[2]EBAQBwcQ[2d]EBAQEBAH[2]EBAQEBAHBwcQ[2]EBAQEAcH[2e]EBAQBxAQ[2]EBAQBwcH[2]EBAQEBAH[2e]EBAQBwcQ[2]EBAQEAcHBxAQ[30]EBAQEAcH[2]EBAQEBAHBxAQ[2d]EBAQEBAH[2]EBAQEBAHBxAQ[2]EBAQEAcQ[2d]EBAQEBAHBxAQ[2]EBAQBwcQ[31]EBAQBwcQ[2]EBAQEBAH[2e]EBAQEAcQ[2]EBAQEAcH[31]EBAQEAcH[3]EBAQBxAQ[2d]EBAQEBAH[2]EBAQEBAHBxAQ[31]EBAQBwcQEBAQEBAHBwcQ[2]EBAQEAcQ[2b]EBAQBwcQ[2]EBAQEAcH[2]EBAQBwcQ[2]EBAQEAcH[28]EBAQBwcQ[2]EBAQEAcH[5]EBAQEAcQ[2]EBAQEAcH[28]EBAQEAcH[2]EBAQEBAHBxAQ[4]EBAQEAcQ[2]EBAQEBAHBxAQ[24]EBAQEBAH[2]EBAQEBAHBxAQ[a]EBAQEBAHBxAQ[2]EBAQEAcQ[1e]EBAQEBAH[3]EBAQBwcQ[2]EBAQEAcQ[b]EBAQBwcQ[2]EBAQEAcQ[1f]EBAQBxAQ[2]EBAQEAcQ[11]EBAQEAcH[1f]EBAQEAcQ[14]EBAQEBAH[3]EBAQBxAQ[1b]EBAQEBAH[18]EBAQBxAQ[2]EBAQEBAH[16]EBAQBxAQ[1a]EBAQEAcQ[3]EBAQBxAQ[15]EBAQEAcQ[1d]EBAQEBAH[3]EBAQEAcQ[f]EBAQEAcQ[28]EBAQBxAQ[b]EBAQEBAH[32]EBAQ",
    },
    {
        offset: {
            i: -7,
            j: -4,
            k: 0,
        },
        wI: 13,
        dJ: 12,
        hK: 15,
        dataString:
            "[13]EBAQEBAH[33]EBAQEBAH[33]EBAQEBAH[33]EBAQEBAH[33]EBAQEBAH[33]EBAQEBAH[e]EBAQEAcQ[24]EBAQEBAH[4]EBAQEAcQ[9]EBAQEAcQ[24]EBAQEBAH[4]EBAQEAcQ[9]EBAQEAcQ[24]EBAQEBAH[4]EBAQBwcQEBAQEAcQ[7]EBAQBxAQ[8]EBAQEBAH[3]EBAQEBAH[18]EBAQBxAQ[2]EBAQEBAHEAcH[2]EBAQEAcHEBAQEAcQEBAQBwcQ[2]EBAQBxAQEAcQ[3]EBAQEBAH[24]EBAQEAcQ[4]EBAQBxAQ[3]EBAQEAcQ[26]EBAQBxAQ[8]EBAQEAcQ[19]EBAQEBAH[3]EBAQEBAH[7]EBAQEBAH[9]EBAQEAcQ[21]EBAQEAcQ[3]EBAQEAcQ[33]EBAQEAcQ[28]EBAQ",
    },
    {
        offset: {
            i: 0,
            j: 0,
            k: 0,
        },
        wI: 2,
        dJ: 2,
        hK: 4,
        dataString: "[4]BwcHEBAH[1]Bw==",
    },
    {
        offset: {
            i: -2,
            j: -2,
            k: 0,
        },
        wI: 4,
        dJ: 4,
        hK: 13,
        dataString: "[3]EBAQEAcQEBAH[2]EBAQEAcQEAcHBxAHBwcQEBAQ[2]EBAHBwcQBwcH[2]EBAQBxAQBwcHEAcHBxAQEBAQEAcQEAcHBxAHBwcQ[2]EBAQEBAHBwcQBwcHEBAQEBAHEBAQBwcQ[3]EBAQBxAQEAcH[3]EBAQBwcQEBAH[3]EBAQEBAH[5]EBAQBxAQ[2]EBAQEBAH[5]EBAQBxAQ[4]EBAQ[1]EA==",
    },
    {
        offset: {
            i: -18,
            j: -9,
            k: 0,
        },
        wI: 32,
        dJ: 26,
        hK: 29,
        dataString:
            "[5b]EBAQEAcQ[a]EBAQBwcQ[109]EBAQEBAHBxAQ[9]EBAQEAcH[10a]EBAQBwcQ[9]EBAQEBAHBxAQ[109]EBAQEAcH[a]EBAQBwcQ[109]EBAQEBAHBxAQ[9]EBAQEAcH[10a]EBAQBwcQ[9]EBAQEBAHBxAQ[109]EBAQEAcH[a]EBAQBwcQ[109]EBAQEBAHBxAQ[9]EBAQEAcH[10a]EBAQBwcQ[9]EBAQEBAHBxAQ[109]EBAQEAcH[9]EBAQEBAHBwcQ[109]EBAQEBAHBxAQ[9]EBAQBwcH[9]EBAQEBAH[c7]EBAQEBAH[42]EBAQEAcHBxAQ[9]EBAQBxAQ[c7]EBAQEAcQ[41]EBAQEAcHBwcQ[9]EBAQBwcQBxAQ[9]EBAQBwcQ[bc]EBAQEBAH[41]EBAQ[2]EAcH[9]EBAQBwcHEAcH[9]EBAQEAcHEAcQ[9]EBAQEAcH[a]EBAQEAcQ[9c]EBAQBxAQ[15]EBAQBxAQ[2c]EBAQEAcQ[8]EBAQEAcHEBAHBxAQ[8]EBAQBwcQEBAHBxAQ[9]EBAQEAcHBxAQ[8]EBAQEBAHBwcH[9]EBAQEBAHBwcQ[9]EBAQEAcH[86]EBAQEBAH[20]EBAQEAcQ[2c]EBAQEAcH[8]EBAQEAcHEBAQBwcQ[8]EBAQBwcQ[17]EBAQBwcQ[9]EBAQEBAH[9]EBAQEBAHBxAQ[7b]EBAQBxAQ[35]EBAQEBAH[15]EBAQEAcQEBAQBwcQ[8]EBAQBxAQEBAHBxAQ[7]EBAQEAcH[18]EBAQBxAQ[1e]EBAQEBAH[9]EBAQEBAHBxAQ[9]EBAQBxAH[9c]EBAQEAcHBxAQ[9]EBAQEBAH[c]EBAQEAcH[a]EBAQBwcQ[7]EBAQEAcQ[18]EBAQEBAH[10]EBAQBxAQ[e]EBAQBxAQ[1d]EBAQ[2]EBAH[85]EBAQBwcHBwcQ[7]EBAQEAcHBwcQEBAQEAcQ[1f]EBAQEBAH[2]EBAQBxAQ[9]EBAQEAcQ[c]EBAQEAcQ[a]EBAQEAcQ[f]EBAQEBAH[19]EBAQBxAQEBAQEBAHBwcQ[10]EBAQBxAQ[a]EBAQEBAH[a]EBAQBxAQ[9b]EBAQEBAH[4]EBAQEBAH[7]EBAQEAcQ[2]EBAQEAcQ[6]EBAQEBAH[a]EBAQBxAQ[d]EBAQEAcQ[5]EBAQEAcQ[4]EBAQEAcQ[a]EBAQBwcH[8]EBAQEAcQEBAQEBAH[6]EBAQEBAHEBAQBxAQ[7]EBAQEBAHBxAQ[a]EBAQBwcH[15]EBAQBxAQ[9]EBAQEAcQ[56]EBAQEBAH[a]EBAQEAcQ[a]EBAQEAcQ[a]EBAQBxAQ[9]EBAQEBAH[5]EBAQEAcQ[16]EBAQBxAQ[13]EBAQEBAH[a]EBAQBxAQ[20]EBAQEBAHEBAQBxAQ[a]EBAQEAcQ[13]EBAQBxAQ[1f]EBAQEAcQ[9]EBAQEBAH[68]EBAQEBAH[a]EBAQBxAQ[16]EBAQBxAQ[8]EBAQEBAHEBAQBxAQ[29]EBAQEAcQ[b]EBAQEAcQ[15]EBAQEAcQ[8]EBAQBxAQEBAH[8]EBAQEAcQEBAQEAcQ[9]EBAQEBAH[1e]EBAQEBAH[5e]EBAQEAcQ[a]EBAQEAcQ[a]EBAQEAcQ[14]EBAQBxAQ[2a]EBAQEBAH[16]EBAQBwcQ[15]EBAQEAcQ[7]EBAQEAcQ[2b]EBAQBxAQ[7d]EBAQEBAH[a]EBAQEAcQ[2b]EBAQBxAQ[1f]EBAQEAcHBxAQ[9]EBAQEBAH[b]EBAQEBAH[33]EBAQBxAQ[68]EBAQBxAQ[15]EBAQBxAQ[2a]EBAQEAcQ[2a]EBAQBxAQ[a]EBAQEAcQ[b]EBAQEBAH[a7]EBAQEAcQ[2a]EBAQEBAH[4c]EBAQEBAH[92]EBAQBxAQ[35]EBAQBxAQ[de]EBAQEBAH[35]EBAQEAcQ[df]EBAQBxAQ[a4]EBAQ[1]EBA=",
    },
    {
        offset: {
            i: -5,
            j: -5,
            k: 0,
        },
        wI: 11,
        dJ: 7,
        hK: 18,
        dataString:
            "[14]EBAQBxAQ[2]EBAQEBAH[15]EBAQEAcH[3]EBAQEAcQ[15]EBAQBwcQ[3]EBAQBxAQ[14]EBAQEBAHBxAQ[2]EBAQEBAH[15]EBAQEAcH[3]EBAQEAcQ[15]EBAQBwcQ[3]EBAQBxAQ[11]EBAQEAcQ[2]EBAQEBAHBwcQ[2]EBAQEBAH[12]EBAQBwcQ[2]EBAQEAcHBxAQ[2]EBAQEAcQ[11]EBAQEBAHBxAQ[2]EBAQBwcH[14]EBAQ[2]EAcH[3]EBAQBwcQ[10]EBAQBxAQ[4]EBAQBwcQ[3]EBAQBxAQ[8]EBAQBwcQ[3]EBAQBxAQ[8]EBAQBxAQ[8]EBAQEAcQ[10]EBAQBwcQ[3]EBAQEAcQ[3]EBAQEAcQ[11]EBAQBxAQ[18]EBAQEBAH[1c]EBAQEBAH[19]EBAQEAcQ[19]EBAQBxAQ[4]EBAQ",
    },
    {
        offset: {
            i: -4,
            j: -4,
            k: 0,
        },
        wI: 12,
        dJ: 7,
        hK: 18,
        dataString:
            "[d]EBAQBwcH[3]EBAQBwcH[3]EBAQEAcQ[f]EBAQEAcH[3]EBAQBwcHBxAQ[2]EBAQBwcHBxAQ[2]EBAQBwcH[f]EBAQEAcH[3]EBAQBwcHBxAQ[2]EBAQBwcHBxAQ[2]EBAQBwcH[b]EBAQEAcQ[3]EBAQEAcH[3]EBAQBwcHBxAQ[2]EBAQBwcHBxAQ[2]EBAQBwcH[e]EBAQEBAHBwcH[2]EBAQEBAHBwcHBxAQ[2]EBAQBwcHBxAQ[2]EBAQBwcH[7]EBAQEAcQ[3]EBAQBxAQ[2]EBAQEAcHEBAH[2]EBAQEAcHBwcHBxAQ[2]EBAQBwcHBxAQ[2]EBAQEAcH[e]EBAQEAcHEBAHBxAQEBAQ[2]EAcHBwcQ[2]EBAQEAcHBwcQ[2]EBAQEBAHBxAQ[d]EBAQEAcQEBAHBxAQEBAQ[2]EAcHBwcQ[2]EBAQEBAHBwcQ[12]EBAQEBAHBxAQEBAQBwcHEBAHBwcHEBAQEAcQEBAHBwcH[e]EBAQEBAHBxAQEBAQEBAHBwcHBxAQEBAQEAcH[2]BwcH[3]EBAQBwcH[12]EBAQBwcHBxAQ[2]EBAQ[2]BwcH[3]EBAQEAcH[12]EBAQEAcQ[3]EBAQBwcQEAcHBwcQEBAQBwcQEBAHBxAQ[15]EBAQBwcQEBAQBwcHEBAHBwcQEBAQBwcQEBAQBxAQ[15]EBAQEAcHEBAHBwcQEBAQEAcHEBAQBwcQ[3]EBAQEBAH[d]EBAQEAcHEBAQEAcQEBAQEAcHEBAQBwcQ[3]EBAQBwcQ[3]EBAQEAcQ[d]EBAQEAcH[3]EBAQEAcH[17]EBAQEBAH[17]EBAQEAcH[14]EBAQ",
    },
    {
        offset: {
            i: -4,
            j: -4,
            k: 0,
        },
        wI: 8,
        dJ: 5,
        hK: 11,
        dataString: "[c]EBAQBwcQ[9]EBAQEBAH[2]EBAQEAcH[a]EBAQBxAQEBAQEBAHBxAQ[9]EBAQEAcQ[2]EBAQBwcQ[9]EBAQEBAH[2]EBAQEAcH[9]EBAQEBAHBwcQEBAQEBAHBxAQ[2]EBAQEAcQ[2]EBAQEBAHBwcHBxAQEBAHBwcH[2]EBAQBwcQ[3]EBAQBxAQEBAHBxAQ[2]BwcHEBAQBwcHBxAQEBAQBwcQ[5]EBAQBwcQEBAQEBAHBxAQEBAHBwcQEBAQEAcQ[7]EBAQEAcQBwcQEBAQEBAHEBAQBwcQ[2]EBAQEBAHEBAQ[2]EBAH[8]EBAQ[1]EBA=",
    },
    {
        offset: {
            i: -1,
            j: -1,
            k: 0,
        },
        wI: 28,
        dJ: 13,
        hK: 25,
        dataString:
            "[9]EBAQEAcHBxAQ[7]EBAQEBAHBwcQ[65]EBAQEBAH[8]EBAQEBAHBwcQ[8]EBAQBwcH[8]EBAQEBAH[5c]EBAQEBAHBxAQ[8]EBAQBwcH[8]EBAQEAcHBxAQ[8]EBAQBxAQ[5c]EBAQBwcQ[8]EBAQEAcHBxAQ[7]EBAQEBAHBwcQ[8]EBAQEAcQ[5c]EBAQEAcH[8]EBAQEBAHBwcQ[8]EBAQBwcH[8]EBAQEBAH[5c]EBAQEBAHBxAQ[8]EBAQBwcH[8]EBAQEAcHBxAQ[8]EBAQBxAQ[4e]EBAQEBAH[d]EBAQBwcQ[8]EBAQEAcHBxAQ[7]EBAQEBAHBwcQ[8]EBAQEAcQ[4f]EBAQBxAQ[c]EBAQEBAH[8]EBAQEBAHBwcQ[8]EBAQBwcH[8]EBAQEBAH[4f]EBAQEAcQ[a]EBAQEAcQ[b]EBAQEAcHBxAQ[7]EBAQEBAHBwcQ[58]EBAQBxAQ[9]EBAQEAcQ[2]EBAQEBAH[8]EBAQEBAHBwcQ[8]EBAQBwcH[4f]EBAQBxAQ[9]EBAQBxAQ[c]EBAQBxAQ[8]EBAQBwcH[8]EBAQEAcHBxAQ[45]EBAQBxAQ[8]EBAQEAcQ[9]EBAQBxAQ[c]EBAQEBAH[8]EBAQEBAHBwcQ[8]EBAQBwcH[45]EBAQBwcQ[8]EBAQEAcH[20]EBAQBwcHBxAQ[7]EBAQEAcHBwcH[8]EBAQEBAH[3b]EBAQEAcH[8]EBAQEBAHBxAQ[20]EBAQBwcH[8]EBAQEAcHBwcQ[8]EBAQBwcH[3a]EBAQEBAHBxAQ[8]EBAQBxAQ[2a]EBAQBwcHBxAQ[7]EBAQEBAHBwcH[8]EBAQEBAHBxAQ[e]EBAQEAcQ[17]EBAQEBAH[9]EBAQBwcQ[34]EBAQBxAQ[8]EBAQEAcHBxAQ[8]EBAQBwcHBxAQ[7]EBAQEBAHBwcH[4]EBAQBwcQ[3]EBAQEBAHBwcQ[8]EBAQEBAHBwcQ[8]EBAQEAcHBxAQ[8]EBAQEAcH[b]EBAQEBAH[40]EBAQBwcH[4]EBAQEAcHBwcH[8]EBAQBwcHBwcQ[8]EBAQBwcH[8]EBAQEBAHBwcQ[8]EBAQEBAHBxAQEBAQEAcQ[11]EBAQEBAH[37]EBAQBwcQ[6]EBAQBwcHEAcHBwcH[6]EBAQ[2]BwcHBwcQ[1a]EBAQBwcHEBAQEBAH[6]EBAQEBAHBxAQEBAH[48]EBAQEBAHBwcQEAcQ[6]EBAQEAcHBwcHBxAQ[7]EBAQEAcHBwcH[9]EBAQBwcQ[6]EBAQEBAHBxAQEBAH[7]EBAQBwcQ[4c]EBAQBxAQ[6]EBAQEBAHBwcH[8]EBAQEAcHBwcQ[10]EBAQEAcQ[8]EBAQEBAHBxAQ[8]EBAQEAcQ[4b]EBAQEBAH[23]EBAQ[2]BwcHBxAQ[6]EBAQEBAH[4c]EBAQEAcQ[19]EBAQEBAH[6f]EBAQEBAH[70]EBAQBxAQ[6f]EBAQBxAQ[39]EBAQ[1]EA==",
    },
    {
        offset: {
            i: -10,
            j: -9,
            k: 0,
        },
        wI: 20,
        dJ: 18,
        hK: 19,
        dataString:
            "[38]EBAQEAcHBxAQ[4]EBAQEBAHBwcH[5]EBAQEBAHBwcQ[63]EBAQBxAQ[5]EBAQBwcHBxAQ[4]EBAQEBAHBwcH[5]EBAQEAcHBwcQ[5]EBAQEAcH[5d]EBAQBxAQ[5]EBAQBwcHBxAQ[4]EBAQEBAHBwcH[5]EBAQEAcHBwcQ[5]EBAQEAcH[5d]EBAQBxAQ[5]EBAQBwcHBxAQ[4]EBAQEBAHBwcH[5]EBAQEAcHBwcQ[5]EBAQEAcH[5d]EBAQBxAQ[5]EBAQBwcHBxAQ[4]EBAQEBAHBwcH[5]EBAQEAcHBwcQ[5]EBAQEAcH[5d]EBAQBxAQ[5]EBAQBwcHBxAQ[4]EBAQEBAHBwcH[5]EBAQEAcHBwcQ[5]EBAQEAcH[63]EBAQBwcHBxAQ[4]EBAQEBAHBwcH[5]EBAQEBAHBwcQ[62]EBAQEBAHBxAQ[5]EBAQBwcHBxAQ[4]EBAQEBAHBwcH[5]EBAQEBAHBwcQ[3c]EBAQBxAQ[25]EBAQEBAHBxAQ[5]EBAQBwcHBxAQ[4]EBAQEBAHBwcH[5]EBAQEAcHBwcQ[28]EBAQBxAQ[5]EBAQEBAH[d]EBAQBxAQ[26]EBAQBwcQ[5]EBAQBwcHBwcQ[4]EBAQEAcHBwcHBxAQ[4]EBAQBwcHEAcQ[27]EBAQEBAH[14]EBAQBxAQ[26]EBAQEAcQ[5]EBAQEBAHBwcQ[4]EBAQEAcHBwcHBxAQ[4]EBAQBwcH[5]EBAQEBAHBxAQEBAQEBAH[3]EBAQEBAHBxAQ[5]EBAQEBAHBxAQ[5]EBAQEAcH[6]EBAQEAcH[6]EBAQEAcQ[13]EBAQEBAH[6]EBAQEAcQ[20]EBAQEAcH[5]EBAQEBAHBwcQ[4]EBAQ[2]EAcHBwcH[4]EBAQBwcQEBAQEAcQ[3]EBAQEBAHBxAQEBAQEAcQ[3]EBAQEBAHBwcQ[5]EBAQEAcHBxAQ[5]EBAQBwcH[6]EBAQEAcH[1a]EBAQEAcH[6]EBAQBwcQ[5]EBAQEBAHBxAQ[5]EBAQEAcH[6]EBAQBwcQ[5]EBAQEBAHBxAQ[5]EBAQEAcH[6]EBAQBwcH[5]EBAQEBAHBwcH[4]EBAQBxAQEBAQBwcQ[3]EBAQEAcHEBAH[5]EBAQBwcQ[6]EBAQEAcH[6]EBAQBwcQ[5]EBAQEBAH[1b]EBAQEBAH[5]EBAQEBAHBxAQ[5]EBAQEAcH[6]EBAQEAcH[6]EBAQBwcQ[5]EBAQEBAHBxAQ[4]EBAQ[2]EBAH[5]EBAQEAcQBwcH[5]EBAQEAcHBwcQ[5]EBAQBwcQ[4]EBAQEAcHEBAH[4]EBAQEAcHBwcQ[4]EBAQEBAHBwcH[6]EBAQEBAHBxAQ[3]EBAQBwcQEBAQEAcH[14]EBAQEBAH[6]EBAQBwcQ[5]EBAQEBAHBxAQ[5]EBAQEAcH[6]EBAQEAcHBxAQ[5]EBAQEAcH[6]EBAQBxAHBxAQ[5]EBAQBwcH[5]EBAQBwcHBxAQ[4]EBAQEBAHBwcQ[5]EBAQBwcHBxAQ[4]EBAQEBAHBxAQ[3]EBAQEAcHBxAQ[4]EBAQEAcHBwcH[5]EBAQBwcHBwcQBxAQ[c]EBAQBxAQ[d]EBAQEBAH[5]EBAQEBAHEAcQ[d]EBAQEAcQ[5]EBAQEBAHBxAQ[5]EBAQEAcH[6]EBAQEBAH[6]EBAQEAcHBxAQ[4]EBAQ[2]EAcHBxAQ[3]EBAQEBAHBwcQEAcH[4]EBAQ[2]BwcQ[4]EBAQEBAHBxAQ[5]EBAQBxAQ[5]EBAQEAcQ[4]EBAQBxAHBxAQ[5]EBAQBwcQ[6]EBAQEBAH[14]EBAQ[2]EAcQ[6]EBAQEBAH[6]EBAQEAcH[6]EBAQBxAQ[1a]EBAQEBAHBxAQ[5]EBAQEAcHBxAQ[4]EBAQEAcQ[6]EBAQBxAQ[3]EBAQEBAH[2]EBAQBxAQEBAQBxAQEBAHBxAQ[a]EBAQEAcH[1d]EBAQEBAH[d]EBAQEAcHBxAQ[27]EBAQBxAQ[6]EBAQEBAHBxAQ[5]EBAQEBAH[6]EBAQEBAH[3a]EBAQEAcH[27]EBAQEAcQ[36]EBAQ",
    },
    {
        offset: {
            i: -3,
            j: -7,
            k: 0,
        },
        wI: 10,
        dJ: 15,
        hK: 20,
        dataString:
            "[18]EBAQBwcQ[31]EBAQBwcQ[2]EBAQEBAH[2e]EBAQBwcQ[2]EBAQEBAH[2e]EBAQBwcQ[2]EBAQEBAH[2e]EBAQBwcQ[2]EBAQEBAH[2e]EBAQBwcQ[2]EBAQEBAH[2b]EBAQBxAQ[2]EBAQBwcQ[2]EBAQEAcH[2a]EBAQEBAHBxAQ[2]EBAQBwcQ[2]EBAQEAcH[2a]EBAQEBAHBxAQ[2]EBAQEAcQ[2]EBAQEAcH[2]EBAQEBAHBxAQ[26]EBAQEBAHBxAQ[2]EBAQEAcQ[2]EBAQEAcQ[2]EBAQEBAHBxAQ[23]EBAQEBAHBxAQ[2]EBAQBwcQ[8]EBAQEBAHBxAQ[2]EBAQBxAQ[1d]EBAQBxAQ[2]EBAQEAcHBwcQ[2]EBAQBwcH[8]EBAQEBAH[3]EBAQBwcQ[2]EBAQEBAH[1a]EBAQBwcQ[2]EBAQ[2]EAcH[2]EBAQEBAH[c]EBAQBwcQ[2]EBAQEAcHBxAQ[15]EBAQEAcH[2]EBAQEBAHBxAQEAcH[2]EBAQEBAHBxAQ[11]EBAQEBAHBxAQ[2]EBAQBwcQ[f]EBAQBxAQ[2]EBAQEAcH[2]EBAQEBAHBxAQEBAH[3]EBAQBwcQ[15]EBAQBwcQ[2]EBAQEBAHBxAQ[a]EBAQEBAHBxAQ[2]EBAQEAcQ[8]EBAQEAcQ[18]EBAQEBAHBwcHBwcQEBAQBwcQ[8]EBAQBxAQ[b]EBAQEAcQ[21]EBAQEBAH[f]EBAQEBAH[21]EBAQEAcQ[f]EBAQEBAH[1e]EBAQBxAQ[31]EBAQ",
    },
    {
        offset: {
            i: -1,
            j: -10,
            k: 0,
        },
        wI: 19,
        dJ: 15,
        hK: 26,
        dataString:
            "[39]EBAQEAcH[5]EBAQEBAHBxAQ[5]EBAQBwcQ[4b]EBAQBwcQ[5]EBAQBwcHBxAQ[4]EBAQEAcHBwcQ[4]EBAQEBAHBwcH[4b]EBAQBwcQ[5]EBAQBwcHBxAQ[4]EBAQEAcHBwcQ[4]EBAQEBAHBwcH[4b]EBAQBwcQ[5]EBAQBwcHBxAQ[4]EBAQEAcHBwcQ[4]EBAQEBAHBwcH[4b]EBAQBwcQ[5]EBAQBwcHBxAQ[4]EBAQEAcHBwcQ[4]EBAQEBAHBwcH[4b]EBAQBwcQ[5]EBAQBwcHBxAQ[4]EBAQEAcHBwcQ[4]EBAQEBAHBwcH[4b]EBAQBwcQ[5]EBAQBwcHBxAQ[4]EBAQEAcHBwcQ[4]EBAQEBAHBwcH[4b]EBAQEAcQ[5]EBAQEAcHBxAQ[4]EBAQEAcHBwcQ[5]EBAQBwcH[4b]EBAQEAcQ[5]EBAQEAcHBwcQ[4]EBAQEBAHBwcH[5]EBAQBwcH[4b]EBAQEBAH[5]EBAQEAcHBwcQ[4]EBAQEBAHBwcH[5]EBAQEAcHBxAQ[4a]EBAQEBAH[5]EBAQEBAHBwcH[4]EBAQEBAHBwcHBxAQ[4]EBAQEAcHBxAQ[50]EBAQEBAHBwcHBxAQ[4]EBAQBwcHBwcQ[4]EBAQEBAHBwcQ[46]EBAQEAcHBwcH[4]EBAQEAcHBwcQEBAQEBAHEBAQ[2]BwcHBxAQ[3]EBAQ[2]BwcH[4]EBAQEBAHBwcH[46]EBAQEAcHBwcH[2]BxAQ[2]EBAQEAcHBwcH[3]EBAQ[2]BwcHBxAHBwcQ[2]EBAQEAcHBwcHBxAQEAcQ[3]EBAQBwcHBxAQEBAQBxAQ[5]EBAQEAcHBwcH[26]EBAQBxAQ[5]EBAQBxAQ[5]EBAQEAcQ[5]EBAQBwcQ[e]EBAQBwcHBxAQEBAQBwcQ[2]EBAQEAcHBwcH[15]EBAQBxAQ[41]EBAQEAcH[5]EBAQEBAHBxAQ[15]EBAQEAcQ[41]EBAQEAcH[5]EBAQEBAHBxAQ[1c]EBAQBxAQ[34]EBAQEAcQ[5]EBAQEAcHBxAQ[5]EBAQBxAQ[51]EBAQEAcQ[5]EBAQEBAHBxAQ[5]EBAQBxAQ[44]EBAQEAcQ[5]EBAQEBAHBxAQ[5]EBAQBwcQ[5]EBAQEBAH[44]EBAQEBAH[6]EBAQBwcQ[5]EBAQEBAHBxAQ[3d]EBAQEAcQ[5]EBAQEBAH[6]EBAQEAcQ[6]EBAQEAcQ[3d]EBAQEAcQ[5]EBAQEBAH[14]EBAQEAcH[5e]EBAQEAcQ[6]EBAQEAcH[50]EBAQEBAH[5e]EBAQEBAH[4a]EBAQ",
    },
    {
        offset: {
            i: -14,
            j: -2,
            k: 0,
        },
        wI: 25,
        dJ: 15,
        hK: 27,
        dataString:
            "[15]EBAQEAcH[7]EBAQEBAH[6b]EBAQEBAHBwcQ[7]EBAQBwcHBxAQ[6]EBAQEAcHBxAQ[6a]EBAQEBAHBwcQ[7]EBAQBwcHBxAQ[6]EBAQEAcHBxAQ[6a]EBAQEBAHBwcQ[7]EBAQBwcHBxAQ[6]EBAQEAcHBxAQ[6a]EBAQEBAHBwcQ[7]EBAQBwcHBxAQ[6]EBAQEAcHBxAQ[6a]EBAQEBAHBwcQ[7]EBAQBwcH[7]EBAQEAcHBxAQ[7]EBAQBxAQ[6b]EBAQBwcH[7]EBAQEAcHBxAQ[6]EBAQEBAHBwcQ[6b]EBAQBwcQ[7]EBAQBwcHBxAQ[6]EBAQEBAHBwcQ[6b]EBAQBwcQ[7]EBAQBwcHBxAQ[6]EBAQEAcHBxAQ[7]EBAQBxAQ[6a]EBAQEBAHBwcH[7]EBAQBwcHBxAQ[6]EBAQEAcHBwcQ[6a]EBAQEBAHBwcH[6]EBAQEBAHBwcHBxAQ[6]EBAQBwcHBwcQ[6a]EBAQEBAH[7]EBAQEBAHBwcHBxAQ[5]EBAQEBAHBwcHBwcQ[6]EBAQBwcQ[6b]EBAQEBAHBwcHBxAQ[5]EBAQEBAH[2]BwcH[5]EBAQEBAHBwcQEAcHBwcQ[5]EBAQBwcQ[5]EBAQEBAHBxAQBwcQ[6]EBAQBwcQ[7]EBAQBxAQ[f]EBAQEAcQ[3d]EBAQBwcH[7]EBAQEAcHBwcHBxAQ[4]EBAQEBAHBxAQEAcHBwcHBxAQ[3]EBAQEBAHBwcQEBAQEBAHBwcHBxAQ[2]EBAQBwcHBwcQ[3]EBAQBwcHBwcQEBAHBwcHBxAQ[4]EBAQBwcH[8]EBAQBwcQEAcQ[7]EBAQEAcH[3d]EBAQEAcHBxAQ[6]EBAQEBAHBwcQ[7]EBAQ[2]EAcH[4]EBAQEAcH[3]EBAQBwcHBxAQ[2]EBAQEAcHBxAQ[3]EBAQBwcHBxAQEBAQEBAHBxAQ[4]EBAQBwcQ[2]EBAHBxAQ[4]EBAQEAcHEBAQEBAHBxAQ[44]EBAQEAcHBwcH[7]EBAQBwcH[4]EBAQEBAH[2]EBAQEAcH[5]EBAQBwcQ[2]EBAQBxAQ[4]EBAQEBAH[7]EBAQEBAH[5]EBAQ[2]EAcQEBAHBxAQ[4]EBAQEAcH[2]EBAQBxAQ[5]EBAQBwcQ[7]EBAQEAcH[2f]EBAQEAcHBxAQ[5]EBAQEBAHBwcHBxAQ[3]EBAQEAcQ[2]EBAQEAcH[4]EBAQEBAH[2]EBAQEAcH[4]EBAQEBAHBwcQEBAQEBAHBxAQ[23]EBAQBwcQEBAQEAcQ[5]EBAQEAcHEBAQEAcQ[6]EBAQEAcQ[1a]EBAQEBAH[3]EBAQEBAHBxAQ[3]EBAQBxAQ[2]EBAQEBAHBwcQ[3]EBAQEAcQEBAQEBAHBwcHBxAQ[6]EBAQEAcHBwcQ[6]EBAQ[2]EAcH[4]EBAQEAcQEBAQEBAHBxAQ[2b]EBAQEBAH[9]EBAQEBAH[1e]EBAQBxAQ[7]EBAQBwcQ[5]EBAQEBAHBxAQEBAQBxAQ[5]EBAQBwcQBxAQ[6]EBAQ[2]EAcH[4]EBAQEAcQEBAQEBAHBxAQ[7]EBAQBwcQ[7]EBAQBxAQ[3b]EBAQEAcQ[17]EBAQBxAQ[7]EBAQBwcQEBAH[6]EBAQEAcH[7]EBAQEBAHBxAH[7]EBAQEAcQ[3b]EBAQBxAQ[27]EBAQBxAQEBAH[6]EBAQEBAH[8]EBAQBxAH[7]EBAQEAcH[5a]EBAQEBAH[11]EBAQBxAQ[7]EBAQBwcQ[7]EBAQEAcH[6b]EBAQ[2]BxAQ[6]EBAQEBAHEAcQ[7]EBAQEAcH[7]EBAQEBAH[8]EBAQBxAQ[64]EBAQBxAQ[6]EBAQEBAHBxAQ[17]EBAQBxAQ[7]EBAQEAcQ[54]EBAQEAcQ[6]EBAQEBAH[7c]EBAQEBAH[7c]EBAQEBAH[35]EBAQ",
    },
    {
        offset: {
            i: -1,
            j: 0,
            k: 0,
        },
        wI: 2,
        dJ: 2,
        hK: 4,
        dataString: "BwcQBwcHEAcQBxAQBxAH[1]EA==",
    },
    {
        offset: {
            i: -2,
            j: -1,
            k: 0,
        },
        wI: 4,
        dJ: 5,
        hK: 12,
        dataString: "EBAQEBAHBwcQEAcQ[3]EBAQEAcQEAcHBxAHBwcQ[3]EBAQBxAQBwcHEAcHBxAQ[2]EBAQ[2]EBAHBwcQBwcH[3]EBAQEAcQEAcHBxAHBwcQ[4]EBAQBwcHEAcH[4]EBAQEBAHBxAQBwcQEBAH[3]EBAQEAcHEBAHBxAQBwcQ[3]EBAQBxAQEBAQEBAHBxAQ[4]EBAQBxAQEAcQ[4]EBAQEAcQ[2]EBAQEAcQ[6]EBAQ[1]BxAQ",
    },
    {
    "offset": {
        "i": -3,
        "j": -1,
        "k": 0
    },
    "wI": 11,
    "dJ": 5,
    "hK": 14,
    "dataString": "[4]EBAQEBAH[12]EBAQBwcQ[2]EBAQEBAH[e]EBAQEAcH[3]EBAQBxAQ[d]EBAQEBAHBxAQ[2]EBAQEAcQEBAH[6]EBAQEBAH[6]EBAQBwcQ[2]EBAQEBAHBxAQ[3]EBAQEBAH[3]EBAQBxAQ[5]EBAQEAcH[3]EBAQBwcQ[3]EBAQEBAH[a]EBAQEBAH[2]EBAQEBAHEAcQ[d]EBAQ[2]EAcH[2]EBAQBwcHEBAQEAcQ[9]EBAQEBAH[5]EBAQEAcQEBAQBxAQEBAQBxAQBwcHBxAHBwcQEBAQEAcQ[8]EBAQEBAH[6]EBAQEAcQ[b]EBAQBxAQEBAQEBAH[f]EBAQEAcQ[e]EBAQEAcQ[6]EBAQBwcH[11]EBAQEBAH[5]EBAQ[1]EBA="
},
{
    "offset": {
        "i": -18,
        "j": -19,
        "k": 0
    },
    "wI": 43,
    "dJ": 40,
    "hK": 21,
    "dataString": "[116]EBAQEAcH[d]EBAQEBAHBxAQ[22d]EBAQEBAHBxAQ[d]EBAQBwcQ[22e]EBAQBwcQ[d]EBAQEAcH[22e]EBAQEAcH[d]EBAQEBAHBxAQ[22d]EBAQEBAHBxAQ[d]EBAQBwcQ[22e]EBAQBwcQ[d]EBAQEAcH[c5]EBAQEBAH[168]EBAQEAcH[d]EBAQEBAHBxAQ[c5]EBAQBxAQ[1b]EBAQEBAH[14c]EBAQBxAQ[d]EBAQBwcQ[c5]EBAQEBAH[d]EBAQEBAH[15a]EBAQEAcQ[d]EBAQEBAHBxAQ[b6]EBAQEBAH[e]EBAQBxAQ[47]EBAQEBAH[11f]EBAQEBAH[e]EBAQBwcQ[25]EBAQBxAQ[91]EBAQBxAQ[47]EBAQEBAH[20]EBAQEAcQ[10d]EBAQBwcQ[d]EBAQEAcH[d]EBAQEBAHBxAQ[d]EBAQBxAQ[8]EBAQEAcQ[83]EBAQBxAQ[47]EBAQEBAH[e]EBAQEAcQ[2d]EBAQEBAH[f1]EBAQEAcH[d]EBAQEBAHBxAQ[d]EBAQBxAQ[d]EBAQBwcQ[d]EBAQEAcH[8]EBAQEBAH[4]EBAQEBAH[70]EBAQEAcQ[47]EBAQEAcH[e]EBAQBxAQ[4a]EBAQEAcQ[46]EBAQEAcQ[d]EBAQEAcQ[d]EBAQEBAH[71]EBAQEBAHBxAQ[c]EBAQEBAHBxAQ[37]EBAQEBAH[9]EBAQEAcQ[3]EBAQEBAHBxAQ[d]EBAQBwcQ[53]EBAQEAcQ[2a]EBAQEBAH[e]EBAQBxAQ[d]EBAQEAcQ[75]EBAQEBAH[e]EBAQBxAQ[d]EBAQBxAQ[d]EBAQEAcQ[38]EBAQEAcQ[46]EBAQEBAH[d]EBAQEBAHBwcQ[d]EBAQBwcHBwcQ[c]EBAQEAcQ[33]EBAQEAcQ[11]EBAQEBAHBwcQ[c]EBAQEBAHBwcQ[45]EBAQEAcQ[d]EBAQEBAH[e]EBAQBxAQ[d]EBAQEBAH[92]EBAQEBAH[80]EBAQBxAQ[d]EBAQBxAQ[d]EBAQEAcQ[d]EBAQEAcH[d]EBAQEBAHBxAQ[d]EBAQ[2]BwcHBxAQ[b]EBAQEBAH[2]BwcHBxAQ[21]EBAQEAcQ[e]EBAQBwcQ[d]EBAQEBAHBwcH[e]EBAQBwcH[e]EBAQEAcQEBAHBwcQ[c]EBAQEBAHBwcQ[1b]EBAQEAcQ[d]EBAQEAcQ[bd]EBAQEAcQ[1d]EBAQEAcQ[d]EBAQEAcQ[d]EBAQEAcQ[62]EBAQEAcQ[d]EBAQEAcH[6]EBAQEAcQ[7]EBAQBxAQ[5]EBAQEAcQ[7]EBAQEAcQ[5]EBAQBwcQ[9]EBAQBwcQEAcH[2]BwcHBxAQ[9]EBAQBwcH[5]EBAQBxAQ[d]EBAQEBAH[e]EBAQEAcQ[1b]EBAQEBAH[2]BwcH[1e]EBAQBxAHBxAQ[c]EBAQEBAHBwcQ[d]EBAQEAcQ[cb]EBAQEAcQ[1d]EBAQEBAH[d]EBAQEBAH[d]EBAQEBAH[d]EBAQEBAHBxAQ[c]EBAQEBAH[d]EBAQEBAH[38]EBAQEAcQ[d]EBAQEBAH[2f]EBAQEAcHBxAQ[c]EBAQ[2]EAcQ[d]EBAQEBAH[e]EBAQEAcQ[d]EBAQEBAH[e]EBAQBxAQ[137]EBAQBxAQ[29]EBAQEAcQ[29]EBAQBxAQ[d]EBAQBxAQ[d]EBAQEAcQ[3e]EBAQEAcQ[1a9]EBAQEBAH[84]EBAQEBAH[1b8]EBAQBxAQ[76]EBAQBxAQ[1c5]EBAQEBAH[1fa]EBAQ"
},
{
    "offset": {
        "i": -4,
        "j": -21,
        "k": 0
    },
    "wI": 13,
    "dJ": 31,
    "hK": 40,
    "dataString": "[58]EBAQBwcQ[3]EBAQBwcH[3]EBAQEAcHBxAQ[3]EBAQBxAQ[78]EBAQEAcH[3]EBAQEAcHBwcQ[2]EBAQEBAHBwcH[3]EBAQEAcH[78]EBAQEBAHBxAQ[2]EBAQEBAHBwcH[3]EBAQBwcHBxAQ[2]EBAQEBAHBxAQ[78]EBAQBwcQ[3]EBAQBwcHBxAQ[2]EBAQEAcHBwcQ[3]EBAQBwcQ[78]EBAQEAcH[3]EBAQEAcHBwcQ[2]EBAQEBAHBwcH[3]EBAQEAcH[78]EBAQEBAHBxAQ[2]EBAQEBAHBwcH[3]EBAQBwcHBxAQ[2]EBAQEBAHBxAQ[78]EBAQBwcQ[3]EBAQBwcHBxAQ[2]EBAQEAcHBwcQ[3]EBAQBwcQ[78]EBAQEAcH[3]EBAQEAcHBwcQ[2]EBAQEBAHBwcH[3]EBAQEAcH[78]EBAQEBAHBxAQ[2]EBAQEBAHBwcH[3]EBAQBwcHBxAQ[2]EBAQEBAHBxAQ[78]EBAQBwcQ[3]EBAQBwcHBxAQ[2]EBAQEAcHBxAQ[3]EBAQBwcQ[78]EBAQEBAH[3]EBAQEBAHBwcQ[3]EBAQBwcH[7d]EBAQBxAQ[3]EBAQBwcH[3]EBAQEAcHBxAQ[7c]EBAQEAcH[3]EBAQEAcHBxAQ[2]EBAQEBAHBwcQ[7c]EBAQEBAHBxAQ[2]EBAQEBAHBwcQ[3]EBAQEAcH[7d]EBAQBwcQ[3]EBAQEAcHBxAQ[2]EBAQEBAHBxAQ[7c]EBAQEAcH[3]EBAQEBAHBwcQ[3]EBAQBwcH[78]EBAQEBAH[3]EBAQEBAHBxAQ[3]EBAQBwcH[3]EBAQEAcHBxAQ[77]EBAQEBAHBxAQ[3]EBAQBwcH[3]EBAQEAcHBxAQ[3]EBAQBwcQ[73]EBAQEBAHBxAQ[3]EBAQBwcQ[3]EBAQEAcHBxAQ[3]EBAQBwcH[3]EBAQEBAH[6f]EBAQEBAHBxAQ[2]EBAQEBAHBwcQ[3]EBAQEAcH[4]EBAQEAcH[3]EBAQEAcHBxAQ[3]EBAQBxAQ[6a]EBAQEAcH[3]EBAQEBAHBwcQ[3]EBAQEAcH[8]EBAQEBAHBxAQ[3]EBAQBwcQ[2f]EBAQEAcQ[3e]EBAQEBAHBwcQ[3]EBAQBwcH[d]EBAQBwcH[3]EBAQEAcHBxAQ[32]EBAQ[2]BxAQ[35]EBAQEBAHBxAQ[3]EBAQBwcQ[11]EBAQEBAHBxAQ[3]EBAQBwcQ[32]EBAQEAcQ[4]EBAQEBAH[2e]EBAQBxAQ[3]EBAQBwcQ[3]EBAQEBAH[12]EBAQBwcQ[3]EBAQEAcH[2b]EBAQEAcQ[3]EBAQEBAH[6]EBAQEBAH[5]EBAQBxAQ[29]EBAQBwcQ[3]EBAQEAcH[16]EBAQEBAHBxAQ[3]EBAQBxAQ[33]EBAQBxAQ[2]EBAQBxAQEAcQ[3]EBAQEBAH[3]EBAQEBAH[4]EBAQBxAQ[3]EBAQBwcQ[3]EBAQEAcQ[14]EBAQBwcQ[3]EBAQEAcH[1b]EBAQBwcQ[3]EBAQEAcH[3a]EBAQEBAH[5]EBAQBxAQ[3]EBAQBwcH[3]EBAQEAcH[3]EBAQEAcHBxAQ[2]EBAQEBAHBxAQ[2]EBAQEBAHBwcQ[2]EBAQEBAHBwcQ[3]EBAQBwcH[3]EBAQEAcH[1f]EBAQEAcH[4]EBAQBxAQ[3a]EBAQBxAQ[10]EBAQBxAQ[3]EBAQEAcH[3]EBAQEBAHBwcQ[3]EBAQBwcQ[3]EBAQEAcH[3]EBAQEBAHBxAQ[1e]EBAQEBAHBwcQ[3]EBAQEAcQ[3e]EBAQEAcQ[3]EBAQEBAHBxAQ[3]EBAQBwcQ[3]EBAQEAcH[3]EBAQEBAHBxAQ[3]EBAQBwcQ[2c]EBAQEAcH[3]EBAQEBAH[3e]EBAQEBAHBxAQ[3]EBAQBwcQ[3]EBAQEAcQ[39]EBAQEBAHBxAQ[3]EBAQBwcQ[39]EBAQEAcQ[47]EBAQBwcQ[3]EBAQBwcH[3]EBAQEAcH[35]EBAQEAcQ[47]EBAQEBAHBxAQ[2]EBAQEAcHBxAQ[2]EBAQEBAHBxAQ[3]EBAQBxAQ[2c]EBAQEAcQ[4c]EBAQBwcQ[3]EBAQEAcH[3]EBAQBxAQ[3]EBAQBwcQ[2c]EBAQEAcQ[4c]EBAQEAcH[3]EBAQEBAHBxAQ[6]EBAQEAcH[3]EBAQEBAHBxAQ[23]EBAQBxAQ[51]EBAQBxAQ[3]EBAQBwcQ[6]EBAQEBAH[3]EBAQEBAHBxAQ[3]EBAQBwcQ[71]EBAQEAcQ[3]EBAQEAcH[4]EBAQBxAQ[2]EBAQEAcQBxAQ[2]EBAQBwcQEAcQ[2]EBAQ[2]EBAH[3]EBAQEAcH[3]EBAQEBAHBxAQ[3]EBAQBxAQ[68]EBAQBxAQ[7]EBAQBxAQ[19]EBAQBxAQ[3]EBAQEAcQ[63]EBAQBxAQ[85]EBAQEBAH[82]EBAQBxAQ[26]EBAQ[1]EA=="
},
{
    "offset": {
        "i": -2,
        "j": -7,
        "k": 0
    },
    "wI": 10,
    "dJ": 19,
    "hK": 33,
    "dataString": "[14]EBAQEBAH[2]EBAQEBAHBwcQ[37]EBAQEBAH[2]EBAQEBAHBwcQ[2]EBAQBwcH[2]EBAQEAcHBxAQ[34]EBAQBxAQ[2]EBAQBwcH[2]EBAQEAcHBxAQEBAQEBAHBwcQ[34]EBAQEAcQ[2]EBAQEAcHBxAQEBAQEBAHBwcQ[2]EBAQBwcH[34]EBAQEBAH[2]EBAQEBAHBwcQ[2]EBAQBwcH[2]EBAQEAcHBxAQ[34]EBAQBxAQ[2]EBAQBwcH[2]EBAQEAcHBxAQEBAQEBAHBwcQ[34]EBAQEAcQ[2]EBAQEAcHBxAQEBAQEBAHBwcQ[2]EBAQBwcH[34]EBAQEBAH[2]EBAQEBAHBwcQ[2]EBAQBwcH[2]EBAQEAcHBxAQ[34]EBAQBxAQ[2]EBAQBwcH[2]EBAQEAcHBxAQEBAQEBAHBwcQ[34]EBAQEAcH[2]EBAQEAcHBxAQEBAQEBAHBwcQ[2]EBAQEAcQ[34]EBAQEBAHBxAQEBAQEBAHBwcH[2]EBAQBwcH[38]EBAQBwcQ[2]EBAQBwcHBxAQEBAQEBAHBxAQ[37]EBAQEAcHBxAQEBAQEBAHBwcQ[2]EBAQBwcQ[37]EBAQEBAHBxAQ[2]EBAQBwcQ[2]EBAQEAcH[20]EBAQBxAQ[3]EBAQBxAQ[13]EBAQBxAQ[2]EBAQEAcH[2]EBAQEBAHBxAQ[1f]EBAQEAcQ[3]EBAQEAcQ[16]EBAQEBAHBxAQEBAQEBAHBwcQ[2]EBAQEAcQ[1c]EBAQEBAH[3]EBAQEAcQ[17]EBAQBwcQ[2]EBAQBwcH[2]EBAQEBAHBxAQ[1c]EBAQBxAQ[2]EBAQEBAH[17]EBAQEAcQ[2]EBAQEAcHBxAQEBAQEBAHBwcQ[2]EBAQEAcQ[2]EBAQEBAH[16]EBAQEAcH[1e]EBAQBwcQ[2]EBAQEAcH[2]EBAQEBAHBxAQ[2]EBAQBwcQ[2]EBAQEAcH[2]EBAQEBAH[3]EBAQBxAQ[2]EBAQBwcQ[2]EBAQEAcQ[2]EBAQEAcH[2]EBAQEBAHBxAQ[1d]EBAQEAcH[3]EBAQBxAQ[5]EBAQEAcQ[2]EBAQEBAH[3]EBAQBwcQ[2]EBAQBwcQ[2]EBAQEAcH[2]EBAQEBAHBxAQEBAQEBAHBxAQ[2]EBAQBwcQ[1e]EBAQBwcQ[2]EBAQEAcQ[36]EBAQEBAH[4]EBAQEAcH[2]EBAQEBAHBxAQ[35]EBAQEAcHBxAQEBAHBwcHBwcQEBAHBwcH[2]EBAQEAcQ[36]EBAQEAcQEBAQBwcHBxAQEBAQEAcH[36]EBAQEAcQEBAQBwcQ[2]EBAQEAcH[38]EBAQEAcQEBAHEBAQEAcH[3]EBAQBxAQ[34]EBAQEAcHEBAHEBAQEBAHBxAQ[2]EBAQBxAQ[37]EBAQEBAHEBAQBxAQEBAQBwcQ[38]EBAQBxAQ[5]EBAQEAcQ[38]EBAQEAcQ[5]EBAQEBAH[35]EBAQEBAH[5]EBAQEBAH[35]EBAQEBAH[9]EBAQBxAQ[3e]EBAQEAcQ[33]EBAQ"
}
];

export function getTreeVoxelDrawingDataByHeight(h: number): IVoxelDrawingDataSerialized {
    let bestMatch = treesVoxelDrawingDatas[0];
    let bestMatchDiff = Math.abs(h - bestMatch.hK);

    for (let i = 1; i < treesVoxelDrawingDatas.length; i++) {
        const treeData = treesVoxelDrawingDatas[i];
        const diff = Math.abs(h - treeData.hK);
        if (diff < bestMatchDiff) {
            bestMatch = treeData;
            bestMatchDiff = diff;
        }
    }

    return bestMatch;
}

export function getTreeVoxelDrawingDataByIndex(n: number): IVoxelDrawingDataSerialized {
    return treesVoxelDrawingDatas[n % treesVoxelDrawingDatas.length];
}
